### ISSUE TITLE
Uninstalled the extension and the window colour won't go away

### ISSUE THREAD

**Issue by teknotica** [stuartcrobinson/unique-window-colors#27]
Hi,

I installed your extension but uninstalled right away as the colour was too strong, and now they window colour won't go away. It stayed there.

I have checked the `settings.json` to see if there's anything overriding my current theme but even changing themes won't make a difference.

Please find image attached for more details.

How do I get back to my original settings? Thanks!

![Screenshot 2019-09-12 at 12 26 41](https://user-images.githubusercontent.com/354494/64780548-9844e100-d558-11e9-8347-db0286627c7b.png)

**Comment by jehillert** [comment]
The problem persists. Why was this closed?

**Comment by cuongn265** [comment]
Same issue here, you have to delete `.vscode/setting.json` in your root directory instead of VSCode Setting it self.

**Comment by yamyam263** [comment]
> Same issue here, you have to delete `.vscode/setting.json` in your root directory instead of VSCode Setting it self. @jehillert

To clarify, @cuongn265 means the **project's** root directory.

Although [the real solution is to just remove the extension added lines because other extensions might also use the `.vscode/setting.json`. Carelessly deleting might cause more problems](https://github.com/stuartcrobinson/unique-window-colors/issues/17#issuecomment-504474617).
